strategy:
  matrix:
    windows:
      image_name: windows-2019
    linux:
      image_name: ubuntu-20.04

# trigger on every commit in main and every stages:
# the tag is necessary otherwise it doesn't trigger on any tag
trigger:
  branches:
    include: ['master']
  tags:
    include: ['*']

# trigger on every pull request to main
pr:
  - master

pool:
  vmImage: $(image_name)

steps:
  - script: cargo build --release --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
  - script: cargo clippy --all
    displayName: Cargo clippy
  - task: CopyFiles@2
    displayName: Copy assets
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/target/release/'
      contents: |
        libsuper_awesome_crate.a
      targetFolder: '$(Build.BinariesDirectory)'
  - task: ArchiveFiles@2
    displayName: Gather assets
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/super-awesome-crate-$(Build.SourceBranchName)-$(Agent.OS)-$(Agent.OSArchitecture).tar.gz'
  - task: GitHubRelease@0
    displayName: 'GitHub release'
    inputs:
      gitHubConnection: 'imgeorgiev'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      target: '$(build.sourceVersion)'
      tagPattern: 'v*.*.*'
      tag: '$(Build.SourceBranchName)'
      assets: '$(Build.ArtifactStagingDirectory)/super-awesome-crate-$(Build.SourceBranchName)-$(Agent.OS)-$(Agent.OSArchitecture).tar.gz'
      title: '$(Build.SourceBranchName)'
      assetUploadMode: 'replace'
      addChangeLog: true
