strategy:
  matrix:
    windows:
      image_name: windows-2019
    linux:
      image_name: ubuntu-20.04

# trigger on every commit in main
trigger:
  - main

# trigger on every pull request to main
pr:
  - main

pool:
  vmImage: $(image_name)

steps:
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
  - script: cargo clippy --all
    displayName: Cargo clippy
