[package]
name = "super-awesome-crate"
version = "0.1.0"
authors = ["Ignat Georgiev <ignat.m.georgiev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
num-traits = "0.2"
approx = "0.4.0"
